name: Android APK Generator

on:
  push:
    branches:
      - main  # यदि आपकी मुख्य ब्रांच का नाम master है, तो यहाँ master लिखें

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: gradle

    - name: Grant Execute Permission for Gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-android-app-apk
        path: app/build/outputs/apk/debug/*.apk
        
